debug: true
db:
 user: "root"
 pass: "root"
 hostname: "localhost"
 dbname: "simple_op_help"
 port: 3306
msg:
 helperAlert: "&1Another player &9(%PLAYER%) &1needs our help, I'll mark it on your map. &9(/replyhelp %ID% [MESSAGE])"
 questionAdded: "&1Your question was sent!"
 replyAdded: "&1Your reply was sent!"