debug: true
db:
 user: "root"
 pass: "root"
 hostname: "localhost"
 dbname: "easyhelpop"
 port: 3306
msg:
 unansweredReady: "&cThere are unanswered questions from players.  \nUse /viewhelp to answer them."
 replyReceived: "&6%HELPER% &banswered your question!\n  &fYou asked: &a%QUESTION%\n  &fThey replied: &b%ANSWER%"
 helperAlert: "&bPlayer &6%PLAYER% &bneeds our help, &oI'll mark it on your map.&r\n  /viewhelp to see & respond to: &a%MESSAGE%"
 questionAdded: "&bYour question was sent!"
 questionFailure: "&cFailed to ask your question, please try again."
 replyAdded: "&bYour reply was sent!"
 replyFailure: "&cFailed to send your reply, please try again."
 playerUnknown: "&cI can't find that player."
 idUnknown: "&cNo question with that ID exists."
 generalFailure: "&cSomething terrible happened, please try again."
 replyStart: "&bEnter a reply to: &a%QUESTION%.  \n&fType &ncancel&r&f to exit out of prompt."
 ignoreQuestion: "&cYou've chosen to ignore: &a%QUESTION%"
