name: ${project.name}
main: com.bigbrainiac10.easyhelpop.EasyHelpOp
version: ${project.version}
author: bigbrainiac10
authors: [ProgrammerDan]
description: Allow players to request help.
commands:
  helpop:
    description: Send a message for help
    aliases: [ho, ask]
    permission: easyhelpop.requesthelp
    usage: /<command> [MESSAGE]
  viewhelp:
    description: List and reply to questions in an interactive setting.
    permission: easyhelpop.replyhelp
    usage: /<command> [all|id|name [ID|NAME]
permissions:
  easyhelpop.requesthelp:
    description: Allow a player to request help
    default: true
  easyhelpop.replyhelp:
    description: Allow a player to reply to a question
    default: op
  easyhelpop.*:
    description: Grant all easyhelpop permissions
    default: op
    children:
      easyhelpop.replyhelp: true
      easyhelpop.requesthelp: true
