name: SimpleHelpOp
main: com.bigbrainiac10.simplehelpop.SimpleHelpOp
version: 1.0
author: bigbrainiac10
description: Allow players to request help.
commands:
   helpop:
      description: Send a message for help
      permission: simplehelpop.requesthelp
   replyhelp:
      description: Reply to a message for help
      permission: simplehelpop.replyhelp
   viewunanswered:
      description: List all unanswered questions
      permission: simplehelpop.replyhelp
   viewquestion:
      description: View a specific question
      permission: simplehelpop.replyhelp